
// Admin Page

export const MENS_PRODUCT_REQUEST="MENS_PRODUCT_REQUEST";
export const MENS_PRODUCT_FAILURE="MENS_PRODUCT_FAILURE";

export const MENS_POST_PRODUCT_SUCCESS="MENS_POST_PRODUCT_SUCCESS";
export const MENS_GET_PRODUCT_SUCCESS="MENS_GET_PRODUCT_SUCCESS";
export const MENS_DELETE_PRODUCT_SUCCESS="MENS_DELETE_PRODUCT_SUCCESS";







export const WOMENS_PRODUCT_REQUEST="WOMENS_PRODUCT_REQUEST";
export const WOMENS_PRODUCT_FAILURE="WOMENS_PRODUCT_FAILURE";

export const WOMENS_POST_PRODUCT_SUCCESS="WOMENS_POST_PRODUCT_SUCCESS";
export const WOMENS_GET_PRODUCT_SUCCESS="WOMENS_GET_PRODUCT_SUCCESS";
export const WOMENS_DELETE_PRODUCT_SUCCESS="WOMENS_DELETE_PRODUCT_SUCCESS";



export const PRODUCT_REQUEST = 'PRODCUT_REQUEST'
export const PRODUCT_FAILURE = 'PRODCUT_FAILURE'

//post request
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
//get request
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

//patch & delete request
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";


// Admin Login page
 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//Signin and Signup
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

//patch
export const PATCH_SUCCESS = "PATCH_SUCCESS";
